[tool.ruff]
line-length = 88

[tool.ruff.format]
preview = true
quote-style = "single"
docstring-code-format = true

[tool.ruff.lint]
preview = true
select = [
    "E", "W", # pycodestyle
    "F", # pyflakes
    "I", # isort
    "C", # complexity: mccabe + flake8-comprehensions
]
ignore = [
    "E501", # line too long
]

[tool.ruff.lint.flake8-quotes]
docstring-quotes = "double"
inline-quotes = "single"

[tool.ruff.lint.mccabe]
max-complexity = 10

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.isort]
known-first-party = [
    "django_sam",
]
